networks:
  gRPC-API:
    name: gRPC-API

volumes:
  data:
    driver: local

services:
  database:
    image: mysql
    env_file: .env
    networks:
      - gRPC-API
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
