networks:
  golang-api:
    name: golang-api

volumes:
  data:
    driver: local

services:
  database:
    image: mysql
    container_name: mysql
    env_file: .env
    networks:
      - golang-api
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

  api:
    build: .
    container_name: api
    env_file: .env
    networks:
      - golang-api
    depends_on:
      - database
