networks:
  golang-api:
    name: golang-api

volumes:
  data:
    driver: local

services:
  database:
    image: mysql
    env_file: .env
    networks:
      - golang-api
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
